### ISSUE TITLE
using s3 storage

### ISSUE THREAD

**Issue by sibijohn72** [codenotary/immudb#1001]
We setup the environment variables as shown in the document before running the db for the first time. installed immuclient on the same vm and used immuclient to add a key value pair. when we refreshed the S3 storage bucket we used to configure, it was still empty.

We expected to see something in the s3 storage bucket.

Steps to reproduce
create empty s3 bucket. 
create vm 
install immudb on vm
configure s3 storage on vm
run immudb for the first time
install immuclient and use it to set your first key value pair.
refresh s3 storage

**Comment by vchaindz** [comment]
immudb starts writing files in the local storage and syncs the data in chunks (when the file size is reached) or the immudb server is shutting down.
When starting immudb you should see a folder in S3 (based on IMMUDB_S3_PATH_PREFIX) and inside an immudb.identifier file.
Continue to write data into immudb or restart the server and you will see more data on S3.

**Comment by sibijohn72** [comment]
understood,. thank you. closing the issue now :)

**Comment by valeti-taruneswar** [comment]
is there any environment variable to change chunks(file size)

**Comment by jeroiraz** [comment]
> is there any environment variable to change chunks(file size)..?

It's possible to specify the file size at database creation time (https://docs.immudb.io/master/management/database.html#database-creation)
