### ISSUE TITLE
Writes are not available to read when using unique index

### ISSUE THREAD

**Issue by 0ctanium** [codenotary/immudb#1003]
**What happened**
If you are using a table with a unique index. When inserting data, it will not be available when you fetch it. Unless you restart the immudb server.

**What you expected to happen**
When inserting data, it should be available to read immediately after the write is done. 

**How to reproduce it (as minimally and precisely as possible)**
First, create the table
```sql
CREATE TABLE IF NOT EXISTS test(
    id INTEGER AUTO_INCREMENT,
    name VARCHAR[252] NOT NULL,
    PRIMARY KEY ( id)
);

CREATE UNIQUE INDEX ON test(email);
```

then add some data
```sql
INSERT INTO test(uid, ref) VALUES('Jhon')
INSERT INTO test(uid, ref) VALUES('Ben')
INSERT INTO test(uid, ref) VALUES('Marc')
```

Now if you try to select the data:
```sql
immuclient> query SELECT * FROM test
```
it should return nothing.

But if you restart the immudb server and then retry. You should retrieve the data

**Environment**
immudb: 1.0.1

**Comment by jeroiraz** [comment]
Thanks for reporting this @0ctanium!

Upcoming release will have enhanced SQL transaction support and this issue is not reproducible.

It would be great if you can try immudb the branch of this PR: https://github.com/codenotary/immudb/pull/1008
