### ISSUE TITLE
immupopulate

### ISSUE THREAD

**Issue by andrei-lihu** [codenotary/immudb#102]
We need an utility that should populate the database with a specified number of entries. Should get the number of records to be written and should return the amount of time required to populate and confirmation OK.

**Comment by vchain-us-mgmt** [comment]
merged with https://github.com/codenotary/immudb/issues/84

**Comment by vchain-us-mgmt** [comment]
Please rename it immutest

**Comment by padurean** [comment]
@vchain-us-mgmt Renamed to `immutest`.
