### ISSUE TITLE
immuadmin client

### ISSUE THREAD

**Issue by andrei-lihu** [codenotary/immudb#103]

**Comment by padurean** [comment]
Initially only the statistics and status commands will be implemented.
Other commands will be added after full user management is implemented in the immudb server.

**Comment by vchain-us-mgmt** [comment]
The full list of features for immuadmin is the following:
- login/logout
- reset connection credentials
- change password
- get stats and KPIs (ability to retrieve the same data exported to Prometheus)
- create users, connection credentials and assign permission (it depends on user management capabilities to be developed on the server-side)
- start/stop, restart immudb service - requires service management 
- create/restore db backup

**Comment by vchain-us-mgmt** [comment]
Please add the "uptime" metric to the list

**Comment by vchain-us-mgmt** [comment]
Here's a proposal for the immuadmin commands.

The general structure is: >immuadmin [Options] COMMAND [ARG...]

Options:
 -h, --help (returns the help menu)
 -v, --version (returns the version of immuadmin)

Commands:
> immuadmin login (log in to an immudb instance) 
> immuadmin logout (log out from an immudb instance)
> immuadmin status (returns the status of the immudb process)
> immuadmin stats (Display immudb resource usage statistics) 
> immuadmin version (Show the immudb version information)
> immuadmin set [options] ARG 
    options: --immuadmin-password (Change the immuadmin password)
> immuadmin install COMMAND [options] ARG 
    commands: service (Install immuadmin as a service)
    options: --local <absolute path to local binary of immudb> (by default the command tries to download the binary online)
> immuadmin uninstall COMMAND [options] ARG (this command must return a "Are you sure you want to uninstall immudb? [Y/N] and also requires to type in the immuadmin password again)
    commands: service (Install immuadmin as a service)
    options: --remove-files (clean up from all immudb files)
> immuadmin user [option] 
    options: 
         --create (create username or UID (format: <name|uid>))
         --delete (create username or UID (format: <name|uid>))
         --set-permissions read/readwrite (set permissions for username or UID (format: <name|uid>))
> immuadmin backup [option] 
         --file (path and name of the backup file)
> immuadmin restore [option] 
         --file (path and name of the backup file)
> immuadmin start (start immudb server)
> immuadmin restart [option] (restart immudb server)
   options: -t, --time (seconds to wait before stopping it)
> immuadmin stop [option] (stop immudb server)
   options: -t, --time (seconds to wait before stopping it)

**Comment by vchain-us-mgmt** [comment]
The graphical view of the stats looks good, except for the two ovals in the middle. Let’s get rid of the ovals and just show them as histograms like HTOP.

**Comment by padurean** [comment]
@vchain-us-mgmt Ok, i will show them using evolving line charts, like the other metrics.
In case you want them differently, here one can see what options are available: https://github.com/gizak/termui

**Comment by vchain-us-mgmt** [comment]
some of the commands in https://docs.google.com/spreadsheets/d/14oMtqfml2nVVDKaq-6j8R8baQNFQDuTt5ijfFocmwro/edit#gid=0 have not been implemented yet. They are highlighted in red.

**Comment by padurean** [comment]
@vchain-us-mgmt `immuadmin version` is already implemented.

**Comment by padurean** [comment]
Closing this. I've added a [separate issue](186)  for the "cold" backup/restore feature.
