### ISSUE TITLE
safeset then safeget doesnt work

### ISSUE THREAD

**Issue by ghost** [codenotary/immudb#105]

**Comment by andrei-lihu** [comment]
PS D:\tmp\windows> .\immuclient safeset key20 value20
index:          20
key:            key20
value:          value20
hash:           6a30094ae5c1b8f1cf618355223595f58d4057d90b2cd7b932b3335e15b4ab4f
time:           2020-04-15 14:26:28 +0200 CEST
PS D:\tmp\windows> .\immuclient safeget key20
index:          20
key:            key20
value:          value20
hash:           6a30094ae5c1b8f1cf618355223595f58d4057d90b2cd7b932b3335e15b4ab4f
time:           2020-04-15 14:26:28 +0200 CEST
verified:       false

**Comment by mmeloni** [comment]
Unable to reproduce. Please provide more details in order to get the error please

**Comment by andrei-lihu** [comment]
Start with an empty database.

**Comment by mmeloni** [comment]
Unable to reproduce again, also with empty db and no .root file. Have you removed .root?
