### ISSUE TITLE
Ruby Library

### ISSUE THREAD

**Issue by ankane** [codenotary/immudb#1078]
Hi, just wanted to share there's now a [Ruby library](https://github.com/ankane/immudb-ruby) for immudb. It uses GRPC and is modeled after the other clients, with a few minor changes to make it more Ruby-like.

If you have any feedback, feel free to let me know here or create an issue in the project. Thanks!

**Comment by jeroiraz** [comment]
hey @ankane, thanks a lot for your contribution! 

Please feel free to share it in immudb Discord channel, so more people get aware of it.

We'll be checking it this week

**Comment by ankane** [comment]
Great. I'm not on Discord, but feel free to post it there. Also, will fix `verified_set`/`verified_get` for immudb 1.2.1 once https://github.com/codenotary/immudb-py/issues/33 is addressed.

**Comment by mmeloni** [comment]
Thanks @ankane You did a great job!

**Comment by zaza81** [comment]
Thanks @ankane, this is a gold contribution. We should make sure it's properly included in docs.immudb.io

**Comment by ankane** [comment]
Thanks, great to hear!
