### ISSUE TITLE
Limit the size of history

### ISSUE THREAD

**Issue by letian0805** [codenotary/immudb#1088]
**What would you like to be added or enhanced**
Limit the size of history
**Why is this needed**
Save on storage costs
**Additional context**
In many business scenarios, it is not necessary to store all historical records, only historical records within a period of time need to be stored. Storing all the history can have a huge cost. Is it possible to delete history records that are out of validity period?

**Comment by Trapfether** [comment]
I can tell you that this probably won't be supported as the entire premise is that there is NO way to truly delete data in this database. Only by physically deleting the files it uses for storage, which will cause the Auditor to trigger a tamper warning the next time it runs. These are critical components of the Auditability and immutability of this approach.

**Comment by jeroiraz** [comment]
thanks for the discussion. In fact, some sort of physical data deletion may be incorporated. There are some use cases that only require the data for a given period of time. Currently expiration and deletions happens at a logical level.

**Comment by letian0805** [comment]
> I can tell you that this probably won't be supported as the entire premise is that there is NO way to truly delete data in this database. Only by physically deleting the files it uses for storage, which will cause the Auditor to trigger a tamper warning the next time it runs. These are critical components of the Auditability and immutability of this approach.

However, there will also be many users who want to use only the cache, sql, and cluster functions of immdb instead of autitor.

**Comment by Svengali** [comment]
Just as a heads up.  It would likely be nice to be able to shard off much older data, just from a data management stand point.
