### ISSUE TITLE
immuadmin hot-backup can't be used in a pipe

### ISSUE THREAD

**Issue by mabmayer** [codenotary/immudb#1092]
**What happened**
When I use immudb hot-backup and don't use the -o option to set an output file, the output goes to stdout. However, also the progress messages "Backing up transactions from 1 to 5585" and "Done" go to stdout, and so getting merged with the output of the backup. When trying to restore such a file, I get the message "Error: malformed backup file".

From my tests it seems, that the check for the malformed backup file is performed _after_ the database for restoration is created, so this would also make it for the user harder to recover from such a situation, when accidentally a wrong file was used for restore. Maybe --append could work, but I didn't test this.

**What you expected to happen**
. Progress messages should go either to stderr or should be generaly suppressed, when stdout is used for backup.
. The format of a backup file should be at least pre-checked at restore, so that in case of accidentally using some broken file, no new database is created (which can not be deleted anymore afterwards).

**How to reproduce it (as minimally and precisely as possible)**
```
immuadmin hot-backup foo | bzip2 > foo.bz2
bzcat foo.bz2 | immuadmin hot-restore bar
```
(didn't test it with that commands, since I'm doing that all through kubernetes, but commands given should be semantically equivalent)

**Comment by qrdl** [comment]
> Progress messages should go either to stderr or should be generaly suppressed, when stdout is used for backup

Progress messages get printed to `stderr`, so they should not interfere with normal backup output.

> The format of a backup file should be at least pre-checked at restore, so that in case of accidentally using some broken file, no new database is created (which can not be deleted anymore afterwards)

There is a possibility to verify correctness of backup file using `immuadmin hot-restore --verify` command. In case of streamed data it is not possible to first verify the whole stream and then restore, because we cannot rewind the stream to the beginning after the verification.

> How to reproduce it (as minimally and precisely as possible) [...]

These commands work fine for me. Can you please show the actual command you are using for backup, @mabmayer ?

**Comment by byo** [comment]
@mabmayer This could be caused by kubectl exec, can you take a look at https://github.com/kubernetes/kubernetes/issues/38998 ?
