### ISSUE TITLE
Playground doesn’t work

### ISSUE THREAD

**Issue by Darwinium** [codenotary/immudb#1110]
**What happened**
Playground doesn’t work (https://play.codenotary.com/) Can’t enter any commands in the terminal there (manually or by clicking play button on the snippets). When you click Clear button (on the top right) you can write something in the “terminal” but you can enter them (When you push Enter on the keyboard it’s just not working)

**How to reproduce it (as minimally and precisely as possible)**
Open https://play.codenotary.com/ in any browser and try to enter commands on the step “Logging in with immuclient”

**Environment**
Last versions of Google Chrome and Safari on MacOS
Also tried on iPad and result the same

**Comment by vchaindz** [comment]
Thanks @Darwinium, we are on it

**Comment by SimoneLazzaris** [comment]
I've checked the logs and the network traffic and it seems that it's a frontend issue, requests are not being sent to the backend: a playground instance is run on the backend, but then it dies because it's not receiving any keepalive command, nor any other input from the browser.

**Comment by zaza81** [comment]
@Darwinium it's fixed, thanks for reporting
