### ISSUE TITLE
Immugw swagger 

### ISSUE THREAD

**Issue by mmeloni** [codenotary/immudb#117]
We need to produce the swagger with immugw customization.

The https://github.com/codenotary/immudb/blob/master/pkg/api/schema/schema.swagger.json is built on top of immudb schema.proto.

The immugw swagger has the following main differences from immudb one:
- immugw has wrapped all safe methods removing root index requirement
- It accepts simple key value and return structured items  with timestamp and structured verified item with also a boolean that proves that verification was ok

**Comment by vchaindz** [comment]
https://github.com/codenotary/immudb/blob/master/pkg/api/schema/gw.schema.swagger.json
