### ISSUE TITLE
SQL better exception 

### ISSUE THREAD

**Issue by Razikus** [codenotary/immudb#1186]
**What would you like to be added or enhanced**

When SQL column doesn't exists the error description is not enough to know where the error for real is

```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
status = StatusCode.UNKNOWN
details = "column does not exist"
debug_error_string = "{"created":"@1650366761.725664627","description":"Error received from peer ipv6:[::1]:3322","file":"src/core/lib/surface/call.cc","file_line":903,"grpc_message":"column does not exist","grpc_status":2}"
```

It should include at least missing column name

**Why is this needed**

Faster exception handling

**Comment by jeroiraz** [comment]
thanks for reporting this @Razikus 

An ongoing PR may cover most of the cases already (https://github.com/codenotary/immudb/pull/1096), it may be merged into master soon
