### ISSUE TITLE
immdb metrics generation

### ISSUE THREAD

**Issue by vchain-us-mgmt** [codenotary/immudb#121]
The following metrics should be available for immudb:
- performance KPIs: average query time, latency, duration
- status (health-check): listener up, badger up, and all statistics from underlying badger
- db size
- number of records  
- number of clients connected to the db
- last client connected
- data status: 
   - integrity check (this is the output produced by the integrity detector)
   - consistency check

**Comment by padurean** [comment]
Hi @filippodm 
I suppose this is related to the _Status_ section in the initial requirements document for _**immuadmin**_ client which states:

>**Status:**
  **Command statistics(about database status):**
    - Data status: consistency, tampered or not; here we should run consistency with the last root from server and its index to get this information
    - How many records and the size of the database (read from disk)
    - database name, database location
  **Command status(about server status):**
    - Configuration settings: mtls status, immudb server ip
    - Healthcheck: listener up, badger up, and all statistics from underlying badger
    - last access and by who

However, the items in the description of this task do not fit perfectly with the above and i am a bit confused which one is the correct, more complete.

**Comment by vchain-us-mgmt** [comment]
The metrics should be available to both immuadmin and to the Prometheus export.  Let's focus on generating the metrics for now and then we decide what command of immuadmin returns which metric. 

I've updated the list of metrics to be consistent with the immuadmin doc.
