### ISSUE TITLE
SDK doc update for Ruby

### ISSUE THREAD

**Issue by ankane** [codenotary/immudb#1250]
Hi, a new version of the [Ruby library](https://github.com/ankane/immudb-ruby) is out that supports verification for immudb 1.2.1+ (in addition to earlier immudb versions) 🎉 

I didn't see a repo for the [SDK docs](https://docs.immudb.io/master/getstarted/jumpstart.html), but would be good to remove the note about verification not working. Also, for the "immudb version" column, the library supports immudb 1.0+ (including 1.3.0). Thanks!

**Comment by jeroiraz** [comment]
Thanks a lot @ankane!

Doc repo is here: https://github.com/codenotary/immudb.io

We'll update it asap

**Comment by ankane** [comment]
Great, thanks @jeroiraz!
