### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by hajsf** [codenotary/immudb#1271]
It looks I changed the password at some point of time, and tried to login today, but looks I forgot it.

Is there a way to reover it, or what shall I do to login again?

<img width="763" alt="image" src="https://user-images.githubusercontent.com/98168280/178071415-5f6d7d52-4086-47ad-b591-e1e6cc564dd4.png">

**Comment by emkaminsk** [comment]
- Add a document
- judge if a tool to recover password can be added
