### ISSUE TITLE
Logger customization

### ISSUE THREAD

**Issue by hajsf** [codenotary/immudb#1272]
An option to customize the lover could be required.

A "Debug" option to show/hide the debug info from the terminal at Key-value embeded database (and whereever possible) is needed.

**Comment by byo** [comment]
On the embedded level it's possible to change the logger with store options: https://pkg.go.dev/github.com/codenotary/immudb@v1.3.1/embedded/store#Options.WithLogger.

By default the verbosity of the immudb standalone server can be changed using `LOG_LEVEL` environment variable (see https://github.com/codenotary/immudb/blob/master/pkg/logger/logger.go#L44)
