### ISSUE TITLE
webconsole doesn't detect if immudb is down, and instead tries to communicate with it. 

### ISSUE THREAD

**Issue by moshix** [codenotary/immudb#1307]
**What happened**
I log into the webconsole. Then I shut down immudb. The webconsole doesn't tell me that immudb is down, and instead attempts the various function like add test data etc, without giving an appropriate message. 

**What you expected to happen**
It should say "unable to communicate with immudb. Is it down?"

**How to reproduce it (as minimally and precisely as possible)**
as above

**Environment**
```shell
# run "immu* version" and copy/paste the output here
```

**Additional info (any other context about the problem)**

**Comment by arriqaaq** [comment]
Needs support from front end team
