### ISSUE TITLE
company name in webconsole is spelled wrong. 

### ISSUE THREAD

**Issue by moshix** [codenotary/immudb#1308]
**What happened**
it says 2 [CodeNotary, Inc](https://www.codenotary.com/)
**What you expected to happen**
Instead it should say Codenotary Inc (no capital N)
**How to reproduce it (as minimally and precisely as possible)**

**Environment**
```shell
# run "immu* version" and copy/paste the output here
```

**Additional info (any other context about the problem)**

**Comment by arriqaaq** [comment]
This seems to be the case right from our license to builds, everything is labelled as `CodeNotary, Inc`. Should this be changed everywhere? @tomekkolo

**Comment by tomekkolo** [comment]
yes
