### ISSUE TITLE
[Feat] Immudb 1.4 release notes

### ISSUE THREAD

**Issue by tomekkolo** [codenotary/immudb#1340]

**Comment by byo** [comment]
# Release notes

We're pleased to introduce new immudb release: 1.4.0. This one comes with two major features: FIPS-compliant builds and Synchronous replication. And as usual there's a lot of smaller improvements and bug fixes.

## FIPS-compliant builds

The Federal Information Processing Standard (FIPS) 140-2 publication describes United States government approved security requirements for cryptographic modules. FIPS-140 series is a collection of computer security standards set by the National Institute of Standards and Technology (NIST) for the United States government. FIPS 140–2 defines the critical security parameters vendors must use for encryption before selling into the U.S government.

Starting with version 1.4.0 immudb can now be compiled using [go-boringcrypto] fork of the golang compiler that uses FIPS 140-2 compliant [boringssl] library. We also provide official FIPS-compliant binaries and docker images.

[go-boringcrypto]: https://github.com/golang/go/blob/dev.boringcrypto/README.boringcrypto.md
[boringssl]: https://boringssl.googlesource.com/boringssl/+/master/crypto/fipsmodule/FIPS.md

## Syncronous replication

Before 1.4.0 version immudb only supported asynchronous replication, replicas could lag behind the primary and any transaction committed on the primary node was not guaranteed to be replicated to replicas in reasonable time.

But using asynchronous replication only it is not possible to ensure that all committed transactions are not lost in scenario when the primary node is irrecoverably lost including its data. In the synchronous mode of replication the primary node waits for enough confirmations from replicas before the transaction is fully committed and durably stored in more than one location. This allows creating an immudb cluster that can survive loss of any single node, including the primary one, without clients complaining about diverged state of the database. Such complains would happen if the primary node is lost and a replica that do not have the most recent commits would be promoted to become a new primary node.

**Comment by tomekkolo** [comment]
add note about SDK updates (go documentation, python, .net, node)

**Comment by tomekkolo** [comment]
add a note about immudb-tools updates (at least replicator tool was updated ?)

**Comment by tomekkolo** [comment]
add links to documentation on FIPS and replication

**Comment by byo** [comment]
@NickAnderegg FYI

**Comment by NickAnderegg** [comment]
@byo I've updated the release notes in-place, since that's apparently a thing that GitHub can do now? No content changes, just structural, looks good 👍

**Comment by byo** [comment]
@NickAnderegg I've added some more info about replication speed, can you take a look?

**Comment by NickAnderegg** [comment]
@byo Looks good. Just one typo and a few commas, which I've fixed in-place!
