### ISSUE TITLE
[Question] Replication storage

### ISSUE THREAD

**Issue by DarkNeedle** [codenotary/immudb#1346]
All:

This is not a bug but rather a question. Should I assume in a 3 node ImmuDB setup that if configured to use S3 that each instance must have it's own S3 storage defined not a shared S3 storage area. Assuming such but wanted to be certain.

Thanks

**Comment by jeroiraz** [comment]
Hi @DarkNeedle, it's a good question

You can assign a bucket per instance or multiple immudb instances can share the same bucket as long as they are using a difference prefix (IMMUDB_S3_PATH_PREFIX).

https://docs.immudb.io/master/production/s3-storage.html

### Shared bucket:
```
export IMMUDB_S3_BUCKET_NAME=immudb-bucket
export IMMUDB_S3_PATH_PREFIX=master
./immudb
```

```
export IMMUDB_S3_BUCKET_NAME=immudb-bucket
export IMMUDB_S3_PATH_PREFIX=replica-001
./immudb
```

### Exclusive bucket:
```
export IMMUDB_S3_BUCKET_NAME=immudb-bucket
# optional prefix
export IMMUDB_S3_PATH_PREFIX=immudb
./immudb
```

```
export IMMUDB_S3_BUCKET_NAME=immudb-bucket
# optional prefix
export IMMUDB_S3_PATH_PREFIX=immudb
./immudb
```

My preference would be to assign each instance its own bucket, but it would be worthwhile to analyze the tradeoffs involved.

Related discussion: https://stackoverflow.com/questions/32671484/is-it-better-to-have-multiple-s3-buckets-or-one-bucket-with-sub-folders
