### ISSUE TITLE
immudb deamon

### ISSUE THREAD

**Issue by vchain-us-mgmt** [codenotary/immudb#136]
It must possible to run immudb in the background. For that, we need to deamonize the immudb service for all OS (e.g. no Linux nohup). 
On Windows, this means creating a service on the service registry that can be started and stopped.

Some example of service demonizing are available here:

https://github.com/influxdata/telegraf/blob/817c9a69a94060aece50889c27e7c821a36a6530/plugins/inputs/win_services/win_services.go

In general:
https://github.com/influxdata/telegraf/blob/819481b1955747359f2109794c8df4d9c24c9e60/cmd/telegraf/telegraf.go

For Windows:
https://github.com/influxdata/telegraf/blob/819481b1955747359f2109794c8df4d9c24c9e60/cmd/telegraf/telegraf_windows.go

Service Install:
https://github.com/influxdata/telegraf/blob/cc6c77f3012f2407780bd037a36dbaf9c5cac5a2/scripts/post-install.sh

An example of a daemon package for use with Go (golang) services with no dependencies is available here:
https://github.com/takama/daemon

**Comment by filippodm** [comment]
add a command to run immudb as a deamon, something "immudb -d"
