### ISSUE TITLE
Remove unused stages of immudb Dockerfile

### ISSUE THREAD

**Issue by emkaminsk** [codenotary/immudb#1365]
What needs to be done:
- the main Dockerfile in root directory should have only the basic steps needed to create Docker image with immudb.
- add Dockerfile.distroless to main branch

The main Dockerfile should be clean and best practice.
https://github.com/vchaindz/immudb/pull/1

The purpose is to remove unnecessary stages that slow down the build of a specific binary.
This cleans up the file and reduces size and execution time of a single build. 
The example is the debian-slim dependency in immudb pipeline.

The complex Dockerfile can be stored in a subdirectory and used from there. If it requires a certain version of build-kit it should require it/have a comment on it.

The main Dockerfile in root isn't for internal purposes, it is supposed to be as clear to customers willing to build the product for themselves as possible.

There is also use case for outside vendors such as Elest.io which have a hook on the main Dockerfile and publish a new build whenever a new version is published.

**Comment by emkaminsk** [comment]
@marcosanchotene Is it possible to automate checking all the Dockerfiles in a project if they are working and they are not out of sync with the current product version?

**Comment by byo** [comment]
Steps to do:

- [ ] Move all current dockerfiles to a `build` folder
- [ ] Create a simple main dockerfile for scratch-based immudb only based on the previous dockerfile
- [ ] Add gh actions to build and test the new simplified dockerfile

**Comment by byo** [comment]
I've changed Dockerfiles in https://github.com/codenotary/immudb/pull/1366 - the only thing left is to test docker build on the main Dockerfile in gh actions.
