### ISSUE TITLE
[sync-replication] Unable to set up a replicated database

### ISSUE THREAD

**Issue by SimoneLazzaris** [codenotary/immudb#1385]
**What happened**
I've tried creating a replicated database, but didn't have success.
I end up with an unresponsive database
**What you expected to happen**

**How to reproduce it (as minimally and precisely as possible)**
- master setup:
```sh
./immudb -a 127.0.0.2 --dir data_master -d
export IMMUADMIN_IMMUDB_ADDRESS=127.0.0.2
./immuadmin login immudb
./immuadmin database create bla --replication-sync-followers 1 -a 127.0.0.2
```
- replica setup
```sh
./immudb -a 127.0.0.3 --dir data_slave -d
export IMMUADMIN_IMMUDB_ADDRESS=127.0.0.3
./immuadmin login immudb
./immuadmin database create bla -a 127.0.0.3 --replication-enabled --replication-master-address 127.0.0.2 --replication-master-database bla --replication-follower-username immudb --replication-follower-password immudb
```

- client
```sh
export IMMUCLIENT_IMMUDB_ADDRESS=127.0.0.2
./immuclient login immudb
./immuclient use bla
./immuclient safeset gorilla banana # freezes
```

Tried to kill servers and restart, I had to `kill -9` master instance, since it didn't respond to SIGTERM.
After restart, client still hangs on the `safeset`

**Environment**
```shell
# run "immu* version" and copy/paste the output here
immudb 1.3.2
Commit  : 113f73e4d014ce81b7838b9c7c73151681e4913d
Built at: Tue, 20 Sep 2022 08:53:30 CEST
```

**Additional info (any other context about the problem)**

**Comment by arriqaaq** [comment]
I've been starting the follower server using this command
```
./immudb --replication-enabled=true --replication-follower-password=immudb --replication-follower-username=immudb --replication-master-address=localhost --port=3323 --pgsql-server=false --metrics-server=false
```

I am not sure but here is my guess on why it is blocking. Currently the follower is setup 

```
./immudb -a 127.0.0.3 --dir data_slave -d
```

So the follower does not know who the master is, so because bla database is created with one sync follower, it does not get an ack

**Comment by jeroiraz** [comment]
`--replication-master-port` may be missing, then automatic replication is not enabled. This is not related to new changes, we may need to add more validations on the parameters.
Recently the expected default value for this flag was set. to this situation won't happen here. Nevertheless, further validations and logging will help

**Comment by emkaminsk** [comment]
This issue wasn't linked to a project. @byo can we close it?

**Comment by byo** [comment]
I believe this is fixed now, @SimoneLazzaris can you confirm ?

**Comment by SimoneLazzaris** [comment]
Yes, we can close it
