### ISSUE TITLE
immudb support for rotation

### ISSUE THREAD

**Issue by filippodm** [codenotary/immudb#141]
immudb currently only grows, but it must be possible to rotate and move a certain portion of my main immudb in different long term immudbs

**Comment by leogr** [comment]
Note that immudb should not rotate/prune the merkletree data, otherwise it will not be able anymore to provide proofs to those client which had cached the root before the rotation happened.

**Comment by zaza81** [comment]
@jeroiraz do you think it's still valid and needed? 
Probably we want to delete old records, but this is the task related to GDPR.

**Comment by jeroiraz** [comment]
yes. It's still valid and pending
