### ISSUE TITLE
Test improvements: prefer `require` to `assert`

### ISSUE THREAD

**Issue by byo** [codenotary/immudb#1436]
**What would you like to be added or enhanced**

In our test suite we should prefer `require` to `assert`. `require` will stop the test if the precondition fails which is what we expect in most of the cases.

This change can not be applied automatically though since there may be places where continuing the test if the assertion fails would still be beneficial (e.g. to get better failure context).

Also the usage of `require` on goroutines spawned by the test should be careful. This will stop the goroutine but the test itself will continue to run which may be unexpected.

**Why is this needed**

We should fail tests early which is what `require` provides.

**Comment by Nowikens** [comment]
Hi, I would like to take this issue. I should mention that this would be my first open source issue, and I'm fairly new to golang. Is there a good file to start with?

**Comment by jeroiraz** [comment]
> Hi, I would like to take this issue. I should mention that this would be my first open source issue, and I'm fairly new to golang. Is there a good file to start with?

Hi @Nowikens, it would be great.

Under embedded package all test files rely on require but you may find unit tests under pkg/server or pkg/client still using assert.

E.g. embedded/htree/htree_test.go
