### ISSUE TITLE
Question: Is it intentional that 1.4.0 of the immudb Helm chart is not yet in the index?

### ISSUE THREAD

**Issue by mprimeaux** [codenotary/immudb#1441]
**What happened**

I'm trying to install [1.4.0](https://github.com/codenotary/immudb/blob/master/helm/Chart.yaml) of the immudb Helm chart but it's not in the index.

**What you expected to happen**

I expected to install version 1.4.0.

**How to reproduce it (as minimally and precisely as possible)**

**Environment**

I followed [these](https://github.com/codenotary/immudb#getting-immudb-running-kubernetes) instructions. 
```shell
helm repo add immudb https://packages.codenotary.org/helm
helm repo update
helm install immudb/immudb --generate-name
```

I received the following error:

```shell
Error: INSTALLATION FAILED: chart "immudb" matching 1.4.0 not found in immudb index. (try 'helm repo update'): no chart version found for immudb-1.4.0
```

**Additional info (any other context about the problem)**

I was able to change the `image.tag` value from "" to "1.4.0" to pull down that version of the immudb container image using the "1.3.2" version of the Helm chart and that **seems** to work fine.

**Comment by byo** [comment]
@SimoneLazzaris can you check?

**Comment by mprimeaux** [comment]
Thanks much, @SimoneLazzaris and @byo
