### ISSUE TITLE
Immuclient tampering example

### ISSUE THREAD

**Issue by Otacon27** [codenotary/immudb#1444]
**Is it possible to have an example of the output immuclient proviedes in case of a tampering detection?**

**In other words, what kind of output should I look for in /var/log/immuclient/immuclient.log when tampering is detected?**

**Comment by byo** [comment]
Hi @Otacon27 

Here are some examples with immudb 1.4.0:

1. State on the client diverged from the server

```
$ ./immuclient safeget a
data is corrupted
```

2. State on the client indicates that there should be more transactions on the server (e.g. database was truncated)

```
$ ./immuclient safeget a
 illegal state
$ ./immuclient safeset a a
rpc error: code = InvalidArgument desc = illegal state
```
