### ISSUE TITLE
Demo Page 404

### ISSUE THREAD

**Issue by bryaend** [codenotary/immudb#1464]
https://github.com/codenotary/immudb/blob/e558684c89ec4e05caf271f125241aafac22e580/README.md?plain=1#L49

The demo page is returning a 404 when clicking the link to https://demo.immudb.io/

**Comment by jeroiraz** [comment]
thanks for reporting it @bryaend

**Comment by SimoneLazzaris** [comment]
Service is now up and running again, thanks for you report
