### ISSUE TITLE
Trying to work with sql files

### ISSUE THREAD

**Issue by JonatanAlcaraz** [codenotary/immudb#1772]
Hello, I am testing the tool. Basically what I want is to be able to pass the folder that contains the tables in sql format so that immudb creates them. For some reason I am not being able to make immudb take these files into account when I try to pass them through the compose file with docker. If anyone knows the solution, it would be a great help, thanks

**Comment by jeroiraz** [comment]
Hi @JonatanAlcaraz, thanks for reaching out. Could you please describe the issue you are having in more detail?

Reading sql statements from a file should be possible but there is no direct way to specify a file as input for the sql statements.

Here `https://github.com/codenotary/immudb-client-examples/tree/master/go/stdlib-init-script` you will find a very minimalistic sample reading sql statement from a file. This sample is not using the sdk but the golang stdlib to interact with immudb
