### ISSUE TITLE
Question: History with SQL

### ISSUE THREAD

**Issue by GFrancoeur99** [codenotary/immudb#1789]
I need to access regularly the history of some entries in my SQL database on immudb.

Is there a way to access the history of some entry without knowing its last transaction id?

**Comment by jeroiraz** [comment]
> I need to access regularly the history of some entries in my SQL database on immudb.
> 
> 
> 
> Is there a way to access the history of some entry without knowing its last transaction id?

Hi @GFrancoeur99, the SQL temporal query supports time-based ranges as well (https://docs.immudb.io/master/develop/sql/querying.html)
