### ISSUE TITLE
refactor immuclient tool

### ISSUE THREAD

**Issue by vchain-us-mgmt** [codenotary/immudb#189]
> immuclient version
> help
> immuclient status
> immuclient login <username>
> immuclient logout
> immuclient check-consistency index hash [flags]
> immuclient count prefix [flags]
> immuclient current
> immuclient get key [flags]
> immuclient getByIndex [flags]
> immuclient rawsafeget key [flags]
> immuclient safeget [flags]
> immuclient history key [flags]
> immuclient scan prefix [flags]
> immuclient inclusion index [flags]
> immuclient iscan pagenumber pagesize [flags]
> immuclient set key value [flags]
> immuclient safeset
> immuclient rawsafeset
> immuclient reference refkey key [flags]
> immuclient safereference
> immuclient safezadd
> immuclient zadd
> immuclient zscan

**Comment by vchain-us-mgmt** [comment]
The current version of immuclient provides a series of commands that are overlapping with immuadmin and should only be in immuadmin, so they need to be removed from immuclient. Other commands should be renamed (e.g. ping into status). All code should be reviewed for improvements in quality.

**Comment by vchaindz** [comment]
done in RC-2
