### ISSUE TITLE
immuclient interactive mode

### ISSUE THREAD

**Issue by vchain-us-mgmt** [codenotary/immudb#192]
Immuclient runs in interactive terminal mode if no commad follow the immuclient instruction, i.e. typing:
$ immuclient 

Each line starts as: 
immuclient> 

The user can type in the commands above in the interactive window.
immuclient> safeset k1 v1

to exit the interactive mode the user has to type quit, or exit or press "Ctrl-C"

see https://sqlite.org/cli.html as reference example

**Comment by vchaindz** [comment]
done in RC-2
