### ISSUE TITLE
SQL (HISTORY OF TABLE) should have "updated_at ", "db_username" for auditing.

### ISSUE THREAD

**Issue by akhtar-a** [codenotary/immudb#1996]
** The current select * from (HISTORY OF TABLE) query in ImmuDB only retrieves the _rev (revision number) for each data change. This proposal aims to enrich the audit trail by including the following additional information:

updated_at: A timestamp indicating the exact time of the data change.
db_username (optional): The username of the database user who made the change (if applicable). **

**
Benefits:
Improved Auditability: Capturing both timestamps and usernames strengthens the audit trail by providing a clear record of "who" and "when" data changes occurred. This facilitates compliance requirements and simplifies investigations in case of discrepancies.
Enhanced Traceability: Timestamps allow for easier tracking of data evolution over time. Additionally, usernames (if implemented) provide context regarding the source of modifications.
**

**Comment by akhtar-a** [comment]
Any Updates ?

**Comment by ostafen** [comment]
Hey, @akhtar-a, the feature you described definetely makes sense. Indeed, we are already working on it and include on the next release

**Comment by akhtar-a** [comment]
Thanks @ostafen  for the response, Looking forward for the next release 
It would also be nicer to have this  [1944](https://github.com/codenotary/immudb/issues/1944)
