### ISSUE TITLE
This download does NOT match the one reported by the checksum server

### ISSUE THREAD

**Issue by EgidioCaprino** [codenotary/immudb#2000]
**What happened**
I tried to install the Go client
```shell
$ go get github.com/codenotary/immudb/pkg/client
go: downloading github.com/codenotary/immudb v1.9.3
go: github.com/codenotary/immudb/pkg/client: github.com/codenotary/immudb@v1.9.3: verifying module: checksum mismatch
        downloaded: h1:kB1HqKQ/hZ2j9y4Xv9nKqIQTlXoGADNxp05iZO4VYdQ=
        sum.golang.org: h1:8ozs0Hejs7HQUNBCCoNgV/Ol0Ztu7FUn4XFe6J9VcHU=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**What you expected to happen**
The client module to be installed correctly.

**How to reproduce it (as minimally and precisely as possible)**
```shell
$ go get github.com/codenotary/immudb/pkg/client
```

**Environment**
The server runs in a Docker container.
![image](https://github.com/codenotary/immudb/assets/5156120/2356795a-0d97-49cd-b256-d2a9fd8156e8)

**Additional info (any other context about the problem)**
None

**Comment by ostafen** [comment]
Hey, @EgidioCaprino, we found out that the `go.sum` corresponding to `v1.9.3` is broken, hence the issue you are getting.
You can fetch the master version for now:
```bash
go get github.com/codenotary/immudb/pkg/client@master
```

**Comment by ostafen** [comment]
Solved with last release
