### ISSUE TITLE
Execute a SQL file

### ISSUE THREAD

**Issue by sleepycat** [codenotary/immudb#2008]
**What would you like to be added or enhanced**

It would be useful to be able to execute a `.sql` file like you can with psql:
```sh
psql --set='sslmode=disable' -h localhost -d defaultdb -U immudb -p 5432 -f demo.sql.
```
**Why is this needed**
This is a useful feature for quickly executing large numbers of SQL statements and is widely supported by most other databases.

**Additional context**

It seems that either the postgres compatibility should support this so the above `psql` command can work or some equivalent command could be added to `immuclient`. Ideally both!

**Comment by ostafen** [comment]
@sleepycat: sounds like the pgsql server is not able to recognize that SSL is disabled when using the
 `--set='sslmode=disable'` option. I will further explore why, but for now a quick fix is to run the following command instead:

```bash
psql "host=localhost user=immudb dbname=defaultdb password=immudb sslmode=disable" -p 5432 -f demo.sql
```
which works as expected.

**Comment by sleepycat** [comment]
That works for me! Thanks.
