### ISSUE TITLE
service <servicename> update

### ISSUE THREAD

**Issue by vchain-us-mgmt** [codenotary/immudb#215]
The user should be able to update the service binaries from immuadmin (ATM he has to uninstall and install it after having built the new binary).

**Comment by Vargo1991** [comment]
Need help fingering out how to get the root to install to root my stylo 5

**Comment by zaza81** [comment]
@mmeloni not clear if this was done in v0.9

**Comment by mmeloni** [comment]
Its obsolete. Now every service has his own installer.
