### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by vchain-us-mgmt** [codenotary/immudb#238]
- build src code
- install distributed binaries 
- run as a daemon 
- a guideline for users to set immudb as a service

**Comment by ankane** [comment]
Hey, just added immudb to Homebrew, so Mac users can do:

```sh
brew install immudb
```

Ref: https://github.com/Homebrew/homebrew-core/pull/55417

**Comment by vchaindz** [comment]
Hey @ankane thanks so much! Highly appreciated!
