### ISSUE TITLE
Check if the version of all commands has been updated accordingly. ATM it is still 0.6.0-rc2

### ISSUE THREAD

**Issue by vchain-us-mgmt** [codenotary/immudb#300]

**Comment by padurean** [comment]
I only updated the Makefile, which means any further builds will produce commands with correct version. However, i did not actually rebuilt & reuoaded the binaries to GitHub. Should i do also that?

**Comment by padurean** [comment]
The versioning mechanism has been fixed. The binaries from GH releases page still show the old version because they haven't been updated.
Once we will release v0.6.1, they will show the correct version.
