### ISSUE TITLE
Binaries not found by imuadmin

### ISSUE THREAD

**Issue by vchain-us-mgmt** [codenotary/immudb#301]
When I download all binaries (that have the version in the name) without renaming them to immudb or immugw, the immuadmin service immu(gw|db) install command does not find a binary

**Comment by padurean** [comment]
@vchain-us-mgmt I don't think this is a bug: one has to use the `--local-file` flag to specify the executable binary. Example: `sudo ./immuadmin service immudb install --local-file immugw-v0.6.0-linux-amd64`.

**Comment by vchain-us-mgmt** [comment]
Please replace the sentence "executable file does not exists or not provided" with "executable file immudb.exe not found in dir ./. Please use the --localfile parameter if your immudb executable has a different name or dir"

**Comment by jeroiraz** [comment]
https://docs.immudb.io/master/running/service.html
