### ISSUE TITLE
Cleanup config files from mixed data

### ISSUE THREAD

**Issue by vchain-us-mgmt** [codenotary/immudb#302]
when installing immudb service the /etc/immudb/immudb.toml file contains mixed immugw/immudb data
address = "127.0.0.1"
auth = false
certificate = "/etc/immudb/mtls/3_application/certs/localhost.cert.pem"
clientcas = "/etc/immudb/mtls/2_intermediate/certs/ca-chain.cert.pem"
dbname = "data"
detached = false
dir = "/var/lib/immudb"
immudb-address = "127.0.0.1"
immudb-port = 3322
logfile = "/var/log/immudb/immudb.log"
mtls = false
network = "tcp"
pidfile = "/var/lib/immudb/immudb.pid"
pkey = "/etc/immudb/mtls/3_application/private/localhost.key.pem"
port = 3322
servername = "localhost"
tokenfile = "token"

**Comment by Gjergj** [comment]
@vchain-us-mgmt is this behavior also on windows?
