### ISSUE TITLE
Curl commands doc, logout, after v0.6.1 is released

### ISSUE THREAD

**Issue by Gjergj** [codenotary/immudb#312]
Add logout curl commands to documentation after v0.6.1 is released.

**Comment by devisions** [comment]
Hi @Gjergj,

I would assume the scope here includes:
1. Update the doc as shown in [immugw > Curl Examples](https://docs.immudb.io/immugw/curl.html) page, whose source is [this](https://github.com/codenotary/immudb.io/blob/master/src/immugw/curl.md) file.
1. Update (regenerate) the [Swagger API](https://github.com/codenotary/immudb/blob/master/pkg/api/schema/schema.swagger.json) spec.

I could send a PR, just to look this weekend to see how that Swagger spec is managed (most probably generated, not manually maintained).

**Comment by jeroiraz** [comment]
Thanks again @devisions. We can always have discussions in slack (open-immutability.slack.com) so we can also provide some hints.

**Comment by devisions** [comment]
Hi @jeroiraz, sure. I am trying to log into that Slack workspace, but it looks like I can't.

As per [this](https://slack.com/intl/en-ro/help/articles/212675257-Join-a-Slack-workspace) article, are there specific email domains allowed or do I need in invitation to be able to join?

**Comment by jeroiraz** [comment]
hi @devisions, please register here https://slack.vchain.us
