### ISSUE TITLE
immugw returns incorrect result on GET request

### ISSUE THREAD

**Issue by Gjergj** [codenotary/immudb#339]
**What happened**
Issuing a GET request to immugw returns bat result in 'value' field
**What you expected to happen**
Return the correct data that was set.
**How to reproduce it (as minimally and precisely as possible)**
`./immudb -s=false`
inside `./immuclient` execute `set k1 Matterhorn`
`./immugw`
`curl --location --request GET 'http://localhost:3323/v1/immurestproxy/item/index/0'`
returns
`{"key":"azE=","value":"CMj6iPcFEgpNYXR0ZXJob3Ju","index":"0"}`
should return
`{"key":"azE=","value":"TWF0dGVyaG9ybg==","index":"0"}`

Immuclient returns the correct result on `get k1`
**Environment**
```shell
immugw 0.6.1
Commit  : 30e371b25c0459dc340759e065c5ebb9d07a68db
Built by: gjergjiramku@gmail.com
Built at: Thu, 11 Jun 2020 15:40:48 CEST
```
```shell
immuclient v0.6.0
Commit  : d115fb52c82d21e6bd1ec4af01eda4fba07caaca
Built by: gjergjiramku@gmail.com
Built at: Thu, 04 Jun 2020 14:28:21 CEST
```
```shell
immudb 0.6.1
Commit  : 30e371b25c0459dc340759e065c5ebb9d07a68db
Built by: gjergjiramku@gmail.com
Built at: Thu, 11 Jun 2020 15:40:48 CEST

```
**Additional info (any other context about the problem)**

**Comment by padurean** [comment]
Weird. `SafeGet` also returns correctly:
![image](https://user-images.githubusercontent.com/912518/84405313-a4a5b980-ac10-11ea-9e05-01b721a131e2.png)

**Comment by Gjergj** [comment]
Do you get the same behavior on `http://localhost:3323/v1/immurestproxy/item/index/0` ?

**Comment by padurean** [comment]
@Gjergj Yes, same wrong value.
