### ISSUE TITLE
Golang SDK immudb

### ISSUE THREAD

**Issue by mmeloni** [codenotary/immudb#34]
Actually immugw rest proxy exposes simplify api that wrap immudb one's.
All safe methods exposes by immugw (SafeSet, SafeGet, SafeReference, SafeZAdd) doesn't require for root and index because this data is managed internally.
The purpose of this task is to create a golang SDK to offer the same capabilities but in pure GO.
It should be fine that immugw wil be upgraded in order to use the newly sdk.
In order to do this you could use a new .proto schema that extends https://github.com/codenotary/immudb/blob/master/pkg/api/schema/schema.proto 
Ex:
actual SafeGet service in immudb schema.proto
```
message SafeGetOptions {
	Key key = 1;
	Index rootIndex = 2;
}
rpc SafeGet(SafeGetOptions) returns (SafeItem){
		option (google.api.http) = {
            post: "/v1/immurestproxy/item/safe/get"
            body: "*"
        };
	};
```
New SafeSet in immu.proto
```
rpc SafeGet(Key) returns (VeridiedItem){};
```
eg: VerifiedItem contains item and a bool in which we put verification results.

Flow:
- The sdk will intercept SafeGet,
- will retrieve rootIndex from client.RootService package
- will forward the call to immudb (with SafeGet(SafeGetOptions) )
- will make checks on result
- will return to the user the VerifiedItem

**Comment by padurean** [comment]
Merged to master.
