### ISSUE TITLE
Immudb crash if stats is running

### ISSUE THREAD

**Issue by mmeloni** [codenotary/immudb#347]
**What happened**
Immudb crash if shoutdown happen when admin stats is running
**What you expected to happen**
Immudb is gracefully shout down
**How to reproduce it (as minimally and precisely as possible)**
Start immudb, launch immuadmin stats and at the end shoutdown immudb without close stats
**Environment**
```shell

immudb 0.6.1
Commit  : 4e1e3c402107d0bb28746765c27d586d889150b5
Built by: cleaversdev@gmail.com
Built at: Mon, 15 Jun 2020 11:26:16 CEST

```

**Additional info (any other context about the problem)**

**Comment by padurean** [comment]
@mmeloni I can not reproduce it. Can you please provide more details? Thanks.
![Jun-15-2020 14-40-53](https://user-images.githubusercontent.com/912518/84653865-d8d1f080-af16-11ea-9c68-97bb1b4522b2.gif)

**Comment by mmeloni** [comment]
Now is working.
