### ISSUE TITLE
Update immutest to support multiple dabatases

### ISSUE THREAD

**Issue by vchain-us-mgmt** [codenotary/immudb#357]
if run as-is it populates the default database with the default user (immudb). The user can decide to use it for a different database. The command would then be:

> immutest // add data to the default database with the default user (immudb). If the password of the default user immudb has been changed, the password will be requested interactively

> immutest --database <database_name> // add data to the specified database using the default user (immudb). If the password of the default user immudb has been changed, the password will be requested interactively

> immutest --database <database_name> --user
<user_name> // add data to the specified database using the <user_name>. In this case it will ask the password interactively

Please update the help (immutest -h) to reflect changes. 
>

**Comment by padurean** [comment]
Implemented in the same [feature branch](https://github.com/codenotary/immudb/tree/feat/multiple_db) that multiple database support is currently implemented.
