### ISSUE TITLE
Change password not working

### ISSUE THREAD

**Issue by mmeloni** [codenotary/immudb#370]
**What happened**
Change password return inconsistent error.

**What you expected to happen**
When I try to change a user password it returns:`old password is incorrect`

**How to reproduce it (as minimally and precisely as possible)**
```
resp2, err2 := client.CreateUser(context.TODO(), []byte(`test`), []byte(`1Password!*`), auth.PermissionRW, "test")
err:= client.ChangePassword(context.TODO(), []byte(`test`), []byte(`1Password!*`), []byte(`2Password!*`))
```
**Environment**
immudb 0.6.2
Commit  : 035845eb26332314f16eb5e1eb7e61adafa8f48c
Built by: cleaversdev@gmail.com
Built at: Thu, 02 Jul 2020 10:25:28 CEST

**Additional info (any other context about the problem)**

Please remember to fix related test inside client_test.go

**Comment by vchain-us-mgmt** [comment]
Retesting with latest codebase needed
