### ISSUE TITLE
List user returns wrong error message

### ISSUE THREAD

**Issue by mmeloni** [codenotary/immudb#372]
**What happened**
When launch ListUser from client package it returns `Single user mode` error.
**What you expected to happen**
We don't have a single mode user, so I expect the list of the users
**How to reproduce it (as minimally and precisely as possible)**
Please see TestUserManagement test inside client_test.go
It's sufficient to launch the test and ispect the results
**Environment**
immudb 0.6.2
Commit  : 035845eb26332314f16eb5e1eb7e61adafa8f48c
Built by: cleaversdev@gmail.com
Built at: Thu, 02 Jul 2020 10:25:28 CEST

**Additional info (any other context about the problem)**
Please correct also test inside client_test.go

**Comment by vchain-us-mgmt** [comment]
Related to #376
