### ISSUE TITLE
UpdateAuthConfig does not reflect changes

### ISSUE THREAD

**Issue by Gjergj** [codenotary/immudb#395]
**What happened**
UpdateAuthConfig does not reflect changes and Auth setting is not changed.
**What you expected to happen**
Change Auth setting to enable or disable Auth
**How to reproduce it (as minimally and precisely as possible)**
Issue can be reproduced in server_test.go,  TestUpdateAuthConfig
**Environment**
```shell
immudb 0.6.2
Commit  : 928bd4b48b1d8f71d912c1bfe262da420074bbed
Built by: gjergjiramku@gmail.com
Built at: Tue, 14 Jul 2020 10:29:39 CEST
```

**Additional info (any other context about the problem)**

**Comment by zaza81** [comment]
@mmeloni  can you confirm this is done?

**Comment by mmeloni** [comment]
Update Auth and UpdateMTLSConfig are not supported on immudb so this should be closed as obsolete. Unluckily ImmuAdmin is not reflecting this and we need to align it.
