### ISSUE TITLE
immuclient ignoring port flags

### ISSUE THREAD

**Issue by ankane** [codenotary/immudb#463]
**What happened**

`immuclient` always uses port 3322, even when `-p` and `--immudb-port` are set.

**What you expected to happen**

It uses the specified port.

**How to reproduce it (as minimally and precisely as possible)**

```sh
 immuclient safeset hello world -p 9000
```

This fails with:

```
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:3322: connect: connection refused"
```

**Environment**

```shell
immuclient 0.7.0
```

**Comment by vchaindz** [comment]
Thanks @ankane - we're already working on fixing it and keep you posted!

**Comment by mmeloni** [comment]
Fixed in https://github.com/codenotary/immudb/commit/83f0b3b09d6792ab012f0c8e12d7a2d45e813ab6

**Comment by ankane** [comment]
Thanks @mmeloni!
