### ISSUE TITLE
immuclient scan wildcard

### ISSUE THREAD

**Issue by vchain-us-mgmt** [codenotary/immudb#505]
Update scan functionality so that it returns the same results when: 
> immuclient scan client
> immuclient scan cli*
> immuclient scan *ent

**Comment by mmeloni** [comment]
`immuclient scan client`
`immuclient scan cli`

are already working, but:

`immuclient scan *ent` is an O(n) complexity operation and shouldn't be issued directly on immudb

**Comment by zaza81** [comment]
@mmeloni I think this is an expected behaviour and a ticket to close, right?

**Comment by mmeloni** [comment]
yes, it's an obsolete ticket
