### ISSUE TITLE
help for immu client

### ISSUE THREAD

**Issue by andrei-lihu** [codenotary/immudb#58]
I should be able to run the following command:
```
./immu --help zscan
```

and get detailed help about the command.

When I type a command in a wrong way I should get correct information. Fow example, as it is no:
````
immudb git:(master) ✗ ./immu zscan
Error: accepts 1 arg(s), received 0
Usage:
  immu zscan set [flags]
Aliases:
  zscan, zscn
Flags:
  -a, --address string   bind address (default "127.0.0.1")
  -h, --help             help for zscan
  -p, --port int         port number (default 3322)
````

from this I understand that zscan is run alone with no argument and some flags: `immu zscan set [flags]`, which is wrong.

Of course, this should be done for all commands.

**Comment by padurean** [comment]
1. It’s `./immu zscan —help`.
2. Mandatory params are not surrounded by any brackets, optional ones are surrounded by square brackets in help output. So in `immu zscan set [flags]` the first mandatory arg is `set`.

**Comment by andrei-lihu** [comment]
Let's do as in man pages. Qquare brackets for optionals and no brackets for required, but let's change the name of `set` to mean the set name.
