### ISSUE TITLE
Scan returns no entries if Desc is true

### ISSUE THREAD

**Issue by padurean** [codenotary/immudb#645]
**What happened**
`./immuclient scan key` returns 2 entries with `Desc: false`, but 0 with `Desc: true`

**What you expected to happen**
`./immuclient scan key` should return 2 entries no matter if `Desc` is `true` or `false`

**How to reproduce it (as minimally and precisely as possible)**
1. Use immuclient CLI to `set` some entries - e.g. with `key1 value1` and `key2 value2`
2. Run `./immuclient scan key` => **2 entries** will be fetched
3. Add `Desc: true` at [line 62 in cmd/immuclient/immuc/scanners.go](https://github.com/codenotary/immudb/blob/dc27e4a6729f26238c3b6a81c3754b506c9efe36/cmd/immuclient/immuc/scanners.go#L62)
4. Rebuild immuclient using `make immuclient`
5. Run `./immuclient scan key` => **0 entries** will be fetched

**Environment**
Latest commit `dc27e4a6729f26238c3b6a81c3754b506c9efe36` from the `master` branch.

**Additional info (any other context about the problem)**

**Comment by jeroiraz** [comment]
Scan uses SeekKey to set the starting point for the scanning. In Asc mode it will iterate over all keys equal (if inclusiveSeek=true) or greater than SeekKey, in Desc mode it will iterate over all keys equal (if inclusiveSeek=true) or lower to SeeklKey. Thus, if SeekKey is nil and Desc is true there will be no keys, a big enough key may be used to ensure all desired keys are included in desc mode. e.g. if keys are composed by a prefix, a separator and a suffix PREFIX . SUFFIX,  SeekKey can be set to a 0xFFFFF (prefix len).

**Comment by padurean** [comment]
@jeroiraz Right, thanks! Now i remember that we've had dis discussion already, but i somehow forgot about it ☺️
I also found examples in my code where i aleeady did the `SeekKey` trick based on the key prefix.
I will close this issue now.
