### ISSUE TITLE
Index cleanup blocking immudb for several minutes

### ISSUE THREAD

**Issue by SimoneLazzaris** [codenotary/immudb#652]
**What happened**
While inserting big volumes of data (1000s of transactions), I've launched an index cleanup.
While the cleanup is execution, data ingestion blocks. Access to previous transaction (get, gettx) is also blocking.
This can take several (3 or 4) minutes.

**What you expected to happen**
I expected to be able to continue data ingestion and/or perform queries during the reindex *or* that the block time would be limited to few seconds.

**How to reproduce it (as minimally and precisely as possible)**
Insert data in close loop using execall. Wait until you have several transaction to be cleaned up. Perform an index cleanup from another client. See that data ingestion halts until reindex termination

**Comment by SimoneLazzaris** [comment]
I will try and provide an executable doing exactly what needed to trigger the issue asap.

**Comment by mabmayer** [comment]
During testing Metrics and Logs I also observed index cleanup to last for several minutes on a approx. 5 G dataset.

**Comment by SimoneLazzaris** [comment]
Indexing now blocks just occasionally and for a few seconds. Insertion while indexing is possible.
As far as I'm concerned, this issue is solved.
