### ISSUE TITLE
Simplify user permissions

### ISSUE THREAD

**Issue by ellisab** [codenotary/immudb#688]
**What would you like to be added or enhanced**
I would like to simplify(possibly make faster) the user permissions

**Why is this needed**
It's an experiment

**Additional context**
This is the code
https://github.com/ellisab/immudb/commit/ad9fea314df54096d783e7dbf812670032d3d8d9
I can do a pull request if it looks good. It needs a migration tool from the slice to the map in order to not break things.

**Comment by ellisab** [comment]
Both in existing code and in my experiment it does not matter what permission **[read|readwrite|admin]** is given in 

> immuadmin user permission revoke testuser **read** test

It will match the database and remove whatever permission was granted on it

**Comment by mmeloni** [comment]
Hi @ellisab, I take a look at your code and it's a good idea, thank you and yes,

> It will match the database and remove whatever permission was granted on it


 that is absolutly a bug that need to be fixed.
