### ISSUE TITLE
Data change example

### ISSUE THREAD

**Issue by hajsf** [codenotary/immudb#697]
I saw your example https://youtu.be/01_wEMdOp1U about writing and reading engineer salary, which looks to be very simple.
my question is:
If later the engineer salary had been increased by 20000$ how can I post this info to the DB, and how can I read the new salary of the engineer?

Simple example how to handle such cases is rquired.

Thanks

**Comment by jeroiraz** [comment]
Thanks for reaching out @hajsf 

Keys can be updated without limitation, currently the entire history of changes to keys get tracked. So following the example it's possible to call UpdateSalary method as many times as needed.

Get will return the latest assigned value. And using History  (https://docs.immudb.io/master/sdks-api.html#history) it's possible to retrieve all the values associated a given key.
 
Extending the examples it's a good idea, meanwhile please let us know if using history operation is clear enough

**Comment by dmacvicar** [comment]
@hajsf As @jeroiraz mentioned, just calling a Set operation with the same key, would update the new salary while keeping the old one in the history. A Get operation would retrieve the latest version. In Pseudocode:

```
SET(employee:001:salary, 1000)
GET(employee:001:salary) -> 1000
SET(employee:001:salary, 2000)
GET(employee:001:salary) -> 2000
```

That means you can use the hello world example described [here](https://github.com/codenotary/immudb-client-examples/tree/master/go) and just set the salary twice.

Let us know if there is an example we can provide to make things more clear, or if you are not using the Go SDK.

**Comment by hajsf** [comment]
> https://docs.immudb.io/master/sdks-api.html#history

It gave me 404 error!

**Comment by dmacvicar** [comment]
https://docs.immudb.io/master/sdk.html#history

**Comment by hajsf** [comment]
Thanks alot
