### ISSUE TITLE
Full support for CRU operations within single transaction

### ISSUE THREAD

**Issue by klausklapper** [codenotary/immudb#704]
Hello there,

I've studied the documentation and had a look at the `GetAll`, `SetAll` and `ExecAll` functions being provided for batch operations. However, there doesn't seem to be a way to run a transaction with support for both reads and writes (as in traditional relational db systems).

Assuming the following hypothetical use case:

- I'm storing a mutable value on a db record (i.e. a currency)
- When making a purchase, I would need to check if the currency is sufficient to afford the purchase
- If so, I want to decrease the value of the currency by the price of the purchase

In a traditional database system, I would combine this logic in a single transaction to ensure atomicity and prevent a possible race condition.

How would I go about ensuring atomicity of my transactions in immudb?

**Comment by jeroiraz** [comment]
Hello @klausklapper, this a very relevant point.

immudb does not provide a way to implement business logic, thus the application needs to handle that.

Having conditional commits might be enough for simple scenarios as the one you describe. Do you think that capability will be useful? If so, would you like to submit a feature request?

**Comment by klausklapper** [comment]
Hey @jeroiraz , thank you for your response.

> Having conditional commits might be enough for simple scenarios as the one you describe. Do you think that capability will be useful?

I can really only speak for myself. I come from a very data integrity critical background and transaction locking on the database level has proven very useful. Of course the client application could place a mutex around the call, but usually that results in more complexity, bugs and hard-to-maintain code.

Transaction locking on a db level has always proven very helpful to me in the past when it comes to ensuring immediate consistency, i.e.

```go
err := client.WithTransaction(func(t *client.tx) error {
    data, err := tx.Select("ACCOUNTS:123:CURRENCY")
    if err != nil { return err }

    if data.balance < 50 { return fmt.Errorf("insufficient funds") }
    
    newBalance := data.balance - 50
    return tx.Set("ACCOUNTS:123:CURRENCY", newBalance)
})
```

Let me know what you think, I'm happy to submit a proper feature request with more background.

**Comment by klausklapper** [comment]
I'm not entirely sure I understand what you're suggesting. The big advantage of database transactions is the ability to wrap multiple statements into an atomic operation. However you imagine `condition` to look and work like will need access to a snapshot of the database, and any of the commits will need to be rolled back in case an error is ocurred. If you manage to support all of this, you basically already have full transactional support. If you don't, then I don't believe the idea of conditional commits will help addressing the problem of atomicity.

I'm not sure how `immudb` is designed when it comes to internal operations. In traditional database systems, every operation is usually automatically wrapped in a transaction and run at a specified [isolation level](https://en.wikipedia.org/wiki/Isolation_(database_systems)) , so it's a core concept of the system.

I don't believe you'll get around a proper implementation if you chose to support this feature. Personally, I'd love to see this being added in the future, as it seems to be the only real blocker I can identify for using this in a production ready environment.

**Comment by zaza81** [comment]
> I'm not entirely sure I understand what you're suggesting. The big advantage of database transactions is the ability to wrap multiple statements into an atomic operation. However you imagine `condition` to look and work like will need access to a snapshot of the database, and any of the commits will need to be rolled back in case an error is ocurred. If you manage to support all of this, you basically already have full transactional support. If you don't, then I don't believe the idea of conditional commits will help addressing the problem of atomicity.
> 
> I'm not sure how `immudb` is designed when it comes to internal operations. In traditional database systems, every operation is usually automatically wrapped in a transaction and run at a specified [isolation level](https://en.wikipedia.org/wiki/Isolation_(database_systems)) , so it's a core concept of the system.
> 
@klausklapper `transactions` as a core feature of the system - as it is designed in traditional relational DBs - is a feature we have in the roadmap. 

> I don't believe you'll get around a proper implementation if you chose to support this feature. Personally, I'd love to see this being added in the future, as it seems to be the only real blocker I can identify for using this in a production ready environment.

Definitely planned for the next releases. Frankly there are other important features we are working on to make a production ready (default db) solution - evolving schemas, better indexing, asynchronous requests for big payloads for example. Thanks for your feedback, we are making our best to deliver the improvements!
