### ISSUE TITLE
Redundancy and remote connection

### ISSUE THREAD

**Issue by Xcaliper** [codenotary/immudb#707]
Is there a tutorial or documentation on the redundancy setup and remote connection?

Need to replicate the database for redundancy set ups.
Meanwhile, remote hosting and connection is also needed if the db is running remotely.

Would really appreciate it if those instructions can be added to quickstart. (Especially remote hosting and connecting)

**Comment by jeroiraz** [comment]
Hi @Xcaliper, thanks for reaching out.

We're continuously working on improving the documentation and the topics you mentioned are quite relevant to be included.

Quick note regarding remote hosting, there shouldn't be any special setting required for a client application to connect to an immudb instance running in a remote server but exposing the port 3322 (or the one configured for immudb) may be needed, either directly or using an http2 proxy.
