### ISSUE TITLE
Stand a lone or supportive tool

### ISSUE THREAD

**Issue by hajsf** [codenotary/immudb#719]
Hi, I got little confused, read something from which 
understood that immudb is a stand a lone db, and so example for that, and in other areas I read something about connection with pgsql, not sure about my understanding, any example how to use immudb with existing pgsql db?

**Comment by mmeloni** [comment]
Hi @hajsf. Yes, immudb is a stand alone db.
In next release (1.0) we will release sql support. It will be possible interact with immudb with sql statements using immudb SDKs or immugw.
In addition we will release also pgsql wire protocol compatibility. This means that immudb could be used as pgsql endpoint. You will able to connect wit psql official cliente for instance.

Another approach is to use immudb as a sidecar for pgsql. Let me check with collegues if we have examples.

**Comment by hajsf** [comment]
Thanks, could you manage a sample?

**Comment by mmeloni** [comment]
Hi @hajsf at the moment we don't have such kind of examples but we are very close to release sql support with multiple examples.

**Comment by hajsf** [comment]
Thanks, awaiting for it, any expected time frame?
