### ISSUE TITLE
How to archive/backup

### ISSUE THREAD

**Issue by hajsf** [codenotary/immudb#722]
How can I archive or backup my immudb, I may need to have it in case there is any issue with my host device.

**Comment by mmeloni** [comment]
Hi @hajsf,
at the moment the easiest way to backup immudb is explained [here](https://docs.immudb.io/0.9.1/immudb/#backup-and-restore)
Please note that we have recently migrate from 0.8 family to the new 0.9 one and immuadmin backap and restore commands are not yet ready for the last version but we are working on them.

**Comment by hajsf** [comment]
Thanks, in the documents it is mentioned the file is saved at `/var/lib/immudb` but in my one it was saved at `./data` by default

![image](https://user-images.githubusercontent.com/46838626/116684929-431e4300-a9ba-11eb-8925-bafcaefcfe08.png)

**Comment by mmeloni** [comment]
@hajsf yes, in the documentation a docker container was used. It's ok data in your case

**Comment by hajsf** [comment]
@mmeloni  how can I change it, I saw something `configs/immudb.toml` but do not know where it is saved.

**Comment by mmeloni** [comment]
You can use `--dir` flag or `IMMUDB_DIR=` environment variable. If you want to use a config file you can specify the path with  `--config` flag.
Let me know if it works for you

**Comment by hajsf** [comment]
mm, I'm new to linux so not sure if I capture it correctly.
once I run `$ ./immudb --config`, I got
```
--config string           config file (default path are configs or $HOME. Default filename is immudb.toml)
```
I could not see anything at `$HOME`, and `configs` does not looks to be a directory!

I'm interested to see the saved one, before creating my own.

**Comment by mmeloni** [comment]
Ok, got it. [here](https://github.com/codenotary/immudb/blob/master/configs/immudb.toml) you find the config shipped with sources of immudb. You can specify config path with:
```
immudb --config /home/user/myconfig.toml
```

**Comment by hajsf** [comment]
Thanks
