### ISSUE TITLE
Hot backups/Restores

### ISSUE THREAD

**Issue by dmacvicar** [codenotary/immudb#742]
A backup mechanism that fetches all the transactions of a database to storage without the need to stop the immudb server.

To take into account:

- Define the serialization format and document it
- It should be able to do incremental backups, if the target already exists, and after validating it corresponds to a previous backup, backup only what is new
- Able to integrate into immuadmin and CNC

Acceptance criteria
- documentation
- export function 
- restore function 
- full backup
- streaming

**Comment by qrdl** [comment]
@jeroiraz @byo @mmeloni
Question(s):

1. CNIL uses separate DB for each ledger. Does user specify db name when doing backup/restore?
2. If not, should backup process all available databases, including `systemdb` and `defaultdb`?
3. If yes, is there any specific order to restore databases? Is there are requirement to restore `systemdb` first?
