### ISSUE TITLE
Enhance CI workflow with web-console

### ISSUE THREAD

**Issue by dmacvicar** [codenotary/immudb#764]
Currently the workflow that builds "make all" does not include the webconsole.

immudb has a web-server on 8080 by default, but if the web-console is not compiled in at build time, it ends like an API server.

The workflow has to be enhanced to get the lastest webconsole artifact:
(https://github.com/codenotary/immudb-webconsole/releases/latest/download/immudb-webconsole.tar.gz) and untar it in webconsole, which should result in a dist/ directory inside webconsole/.

Then make should be called with "make WEBCONSOLE=1" which bundles the "dist" directory inside the executable. Now tests like the one described in https://github.com/codenotary/immudb/issues/763 could also check that the webconsole is available.

**Comment by ufierro** [comment]
I've created branch enh-it-763 for this. This currently covers #763 and #764 however the webconsole repo is missing the pre-built artifact 
![image](https://user-images.githubusercontent.com/13771334/118725927-cf6b9b00-b7ed-11eb-803f-a1e32020b109.png)

so I had to fall back to using the previous version
![image](https://user-images.githubusercontent.com/13771334/118725946-d85c6c80-b7ed-11eb-99d6-37f8c36128a1.png)

I will create a PR but let's not merge for now
