### ISSUE TITLE
Running SQL interactively in immuclient always returns unnecessary warning

### ISSUE THREAD

**Issue by federico-razzoli** [codenotary/immudb#803]
**What happened**

immuclient>exec SELECT id FROM people
INFO: Redunant argument(s) | [id FROM people] 
sql ok, Ctxs: 0 Dtxs: 0

**What you expected to happen**

immuclient understands the command correctly and I can't find a different way to run the same. So I expect no warnings.

**Environment**

1.0.0 (both client and server)

**Comment by jeroiraz** [comment]
Thanks @federico-razzoli 

Please use `query` instead of `exec` to get query results. 

`Redunant argument(s)` warning should not appear and probably improving documentation and hints about `query` vs `exec` operations

**Comment by federico-razzoli** [comment]
Sorry for the incomplete information, but the warning appears with both `query` and `exec`:

```
immuclient>query SELECT * FROM t1
INFO: Redunant argument(s) | [* FROM t1]
```

I tried to wrap the query with quotes to make it appear as a single argument, but it doesn't work.

**Comment by jeroiraz** [comment]
Issue seems to be caused by a limited parsing of arguments.
`cmd/immuclient/cli/cli.go line 121 arrCommandStr := strings.Fields(line)`

Note: using immuclient in non-interactive mode it's possible to quote sql statement
e.g. immuclient query "SELECT * FROM t1"
