### ISSUE TITLE
immuclient help should mention "<command> --help" syntax

### ISSUE THREAD

**Issue by federico-razzoli** [codenotary/immudb#805]
**What would you like to be added or enhanced**

In immuclient, the `help` command shows a list of available commands.

I suggest to add a line to inform us that we can run any command with the `--help` argument (eg: `exec --help`).

**Why is this needed**

It's hard to learn it otherwise.

**Comment by mmeloni** [comment]
It's already present, isnt?
![image](https://user-images.githubusercontent.com/3756718/147920564-3dd58a0e-3212-4f54-88b9-0969d7574cb2.png)

**Comment by zaza81** [comment]
@federico-razzoli can you confirm you see --help for commands as well? In case yes, please close the ticket.
