### ISSUE TITLE
The <column> <type> NULL syntax should be allowed

### ISSUE THREAD

**Issue by federico-razzoli** [codenotary/immudb#806]
**What happened**

```
immuclient>exec CREATE TABLE test (a INTEGER, b INTEGER NULL, PRIMARY KEY a)
INFO: Redunant argument(s) | [TABLE test (a INTEGER, b INTEGER NULL, PRIMARY KEY a)] 
ERROR: rpc error: code = Unknown desc = syntax error: unexpected NULL, expecting ','
```

**What you expected to happen**

In standard SQL and in most DBMSs the above syntax is allowed (though it adds nothing, because columns are NULLable by default).

**Comment by jeroiraz** [comment]
Thanks a lot for opening this issue @federico-razzoli
