### ISSUE TITLE
Do you have plans for distributed platforms?

### ISSUE THREAD

**Issue by rzamoramx** [codenotary/immudb#807]
**What would you like to be added or enhanced**
Would be very nice if this DB will support distributed environments, I mean, like dynamoDb or Firestore which runs and scale horizontally

**Why is this needed**
For real-time and high resilience enterprise systems this feature is very important

**Additional context**

**Comment by dmacvicar** [comment]
@rzamoramx We are not looking to actively develop this ourselves yet. If we do, it may be a separate component as part of our [Immutable Ledger](https://www.codenotary.com/products/immutable-ledger/) product.

If you are interested in contributing this feature, feel free to re-open. You may want to check [our contributing guidelines](https://github.com/codenotary/immudb/blob/master/CONTRIBUTING.md).
