### ISSUE TITLE
SQL transactions not working as expected

### ISSUE THREAD

**Issue by patte** [codenotary/immudb#817]
**What happened**
While trying out immodb I stumbled over the following inconsistencies regarding transactions in SQL. 

**What you expected to happen**
The following commands results have been obtained via the web console (or with psql) from the demo data set.

\
According to the [docs](https://docs.immudb.io/master/reference/sql.html#transactions) the following should should work:
```sql
BEGIN TRANSACTION; UPSERT INTO customers (id, customer_name) VALUES (1, 'asa1') UPSERT INTO products (id, product) VALUES (1, 'juice1') COMMIT;
```
But no data is changed and the following error is thrown:  message: syntax error: unexpected STMT_SEPARATOR 

\
According to the [tests](https://github.com/codenotary/immudb/blob/3023b36f04ff357d65144bc815c9c3d677b18d62/embedded/sql/engine_test.go#L346) the following query should work:
```sql
BEGIN TRANSACTION
  UPSERT INTO customers (id, customer_name) VALUES (1, 'Asa11');
  UPSERT INTO customers (id, customer_name) VALUES (2, 'Neila22');
COMMIT
```
But as it seems the web console sends the commands separately splitted at `;`. So the queries above produce the errors:
1) `syntax error: unexpected $end, expecting COMMIT`
2) no error and customer_name of customer with `id = 2` is set to 'Neila22'
3) syntax error: unexpected COMMIT

\
Testing the same query as just before in `psql` the error behaviour remains the same:
```sql
defaultdb=> BEGIN TRANSACTION
  UPSERT INTO customers (id, customer_name) VALUES (1, 'Asa11');
  UPSERT INTO customers (id, customer_name) VALUES (2, 'Neila22');
COMMIT

ERROR:  syntax error: unexpected $end, expecting COMMIT
ok
```
Notice that in this case the error message indicates that the query didn't work, but customer_name of customer with `id = 2` is silently changed.

\
Trying to do everything on one line doesn't work either:
```sql
defaultdb=> BEGIN TRANSACTION UPSERT INTO customers (id, customer_name) VALUES (1, 'Asa11'); UPSERT INTO customers (id, customer_name) VALUES (2, 'Neila22') COMMIT;

ERROR:  syntax error: unexpected $end, expecting COMMIT
ERROR:  syntax error: unexpected COMMIT 
```

\
So far I didn't find a statement that accomplishes to combine two queries into one transaction.

**How to reproduce it (as minimally and precisely as possible)**
Issue the commands above

**Environment**
```shell
# docker run -d --net host -it --rm --name immudb codenotary/immudb:latest
```
- access the web console at http://localhost:8080
- load demo data
- connect psql: `psql "host=localhost dbname=defaultdb user=immudb password=immudb sslmode=disable"`

latest: v1.0.0

**Comment by jeroiraz** [comment]
thanks @patte for opening the isssue.

I think there is a syntax error, when starting the tx the statement separator is not expected

This should work, note I removed the ';' immediately after `BEGIN TRANSACTION`

`BEGIN TRANSACTION UPSERT INTO customers (id, customer_name) VALUES (1, 'asa1') UPSERT INTO products (id, product) VALUES (1, 'juice1') COMMIT;`

**Comment by patte** [comment]
Thanks @jeroiraz for the prompt reply!

> This should work, note I removed the ';' immediately after `BEGIN TRANSACTION`
> 
> `BEGIN TRANSACTION UPSERT INTO customers (id, customer_name) VALUES (1, 'asa1'); UPSERT INTO products (id, product) VALUES (1, 'juice1') COMMIT;`

I get the following result:
```sql
defaultdb=> BEGIN TRANSACTION UPSERT INTO customers (id, customer_name) VALUES (1, 'asa1'); UPSERT INTO products (id, product) VALUES (1, 'juice1') COMMIT;
ERROR:  syntax error: unexpected $end, expecting COMMIT
ERROR:  syntax error: unexpected COMMIT
```
I get the same result via psql and web admin.

**Comment by federico-razzoli** [comment]
This works:

```
immuclient>{ec BEGIN TRANSACTION insert into tab2 (a) values (11); insert into tab2 (a) values (12); commit; 
INFO: Redunant argument(s) | [TRANSACTION insert into tab2 (a) values (11); insert into tab2 (a) values (12); commit;] 
sql ok, Ctxs: 0 Dtxs: 1
```

Basically I put a `;` after all statements except `BEGIN`.

**Comment by jeroiraz** [comment]
thanks @patte 
Indeed, I'm receiving same error with webconsole, however from immuclient as well from unit testing is working, so it must be something on how webconsole and pgdriver is preparing the statements, we'll address it asap.

Following steps works from immuclient and thus it should work using golang sdk:

```
./immuclient exec "create table customers(id integer, customer_name varchar, primary key id);" 
./immuclient exec "create table products(id integer, product varchar, primary key id);"
./immuclient exec "BEGIN TRANSACTION UPSERT INTO customers (id, customer_name) VALUES (1, 'asa1'); UPSERT INTO products (id, product) VALUES (1, 'juice1');COMMIT;"
````

**Comment by jeroiraz** [comment]
> This works:
> 
> ```
> immuclient>{ec BEGIN TRANSACTION insert into tab2 (a) values (11); insert into tab2 (a) values (12); commit; 
> INFO: Redunant argument(s) | [TRANSACTION insert into tab2 (a) values (11); insert into tab2 (a) values (12); commit;] 
> sql ok, Ctxs: 0 Dtxs: 1
> ```
> 
> Basically I put a `;` after all statements except `BEGIN`.

Actually ';' is needed if there are more than one statement, so it should be optional (but still good practice) in the last statement before COMMIT.
