### ISSUE TITLE
Remove additional blank line from immuclient output

### ISSUE THREAD

**Issue by jeroiraz** [codenotary/immudb#829]
**What happened**

Output generated from immuclient commands includes an additional blank line

e.g.
```
> ./immuclient set k0 v0
tx:		1 
key:		k0 
value:		v0 
hash:		6930a890518dad8804ffcee19d0c0759c4a31040612db8ea12beb7f7231047a0 

>
```

**What you expected to happen**

```
>./immuclient set k0 v0
tx:		1 
key:		k0 
value:		v0 
hash:		6930a890518dad8804ffcee19d0c0759c4a31040612db8ea12beb7f7231047a0
>
```

**Comment by Patil2099** [comment]
I would love to help in solving this issue. Can you guide me a little on solving this issue?

**Comment by jeroiraz** [comment]
probably it's something to fix in 'cmd/immuclient/immuc/print.go' file
