### ISSUE TITLE
Add MacOS ARM64 builds

### ISSUE THREAD

**Issue by DoktorCranium** [codenotary/immudb#845]
Add ARM64 Mach-O builds for Apple Silicon 
People can run immudb natively on the M1 hardware

I have tested this - see https://twitter.com/astr0baby/status/1409144358604058629

**Comment by jeroiraz** [comment]
Thanks @DoktorCranium !

**Comment by byo** [comment]
Hi @DoktorCranium, we've just released the the 1.0.5, can you check if it works on the M1 hardware ?
