### ISSUE TITLE
Remove Appendable.SetOffset for remote storage

### ISSUE THREAD

**Issue by byo** [codenotary/immudb#858]
**What would you like to be added or enhanced**

Currently the `Appendable` interface has a `SetOffset` method which can move the offset back to an older position. It is used to recover from a situation when writing a transaction fails in the middle or is reverted.

**Why is this needed**

The `SetOffset` method does greatly increase the complexity of remote appendable implementation (e.g. it requires re-downloading chunks of data and extra caution when the local file is being removed). Getting rid of this method means that we introduce a guarantee that there's no possibility to change any data that was previously written through the `Append` method (including partially completed writes).

This is a prerequisite to the following functionalities:
* Locking full chunks on the remote storage
* Easier compression, encryption, authentication and error correction data
* Simplifies implementations of the appendable interface (no need to re-download completed chunks)

**Additional context**

When a transaction is written, the following data is written in order:
* Payloads - keys and values
* Transaction header
* Commit record
* AHT tree entries

A data is durably stored at the `commit record` step - once it's synced, the transaction is accepted.
The data write can thus fail in the following steps:
* Writiting payloads - failure here will leave a garbage in the value appendable, no data will be lost but there will be data that will never be read
* Writing transaction header - if this operation fails, there will be garbage in the transaction appendable, such transaction will never be used though and will not cause data inconsistency in already committed data
* Writing commit entry - if this operation fails fully, the transaction won't be completed at all, if this write completes partially, there will be a manual recovery operation necessary to recover from it (even now the client would fail to start properly in this case)
* Writing AHT tree - once the transaction is committed, the AHT tree can be deterministically recomputed. If the write to AHT fails to write anything, AHT tree can still recover the same data based on the committed data. If the write fail partially, the already written part of data will be equal to the prefix of the new data that would have been written if the recovery happened.

In order to correctly handle the partial write on the commit log we should guarantee that the data that's uploaded to a remote storage only happens once there was a fully successful Append operation, partially written data should not be uploaded.

**Comment by jeroiraz** [comment]
If an error occur while writing transaction header, the next transaction will go back up to the previously committed transaction. So in this case, garbage is just temporal

**Comment by byo** [comment]
The only valid use-case for the SetOffset (assuming we can accept the garbage in most cases) is the commit log - it consists of fixed 12-byte entries that must be written atomically - if a write only partially succeeds, the next write must use SetOffset to move the offset back to the boundary of 12-byte entries.

In case of the multi-file appendable the chunk size is usually 64 MB (or 1MB in case of an instance with the remote storage) which means that commit entries will happen across chunk boundaries thus we can not rely on any OS-based mechanism to guarantee atomic write here.

We could however add an extra property to appendable - a record size. Every write to appendable would have to be done on an offset that's a multiple of a record size and the amount of bytes written would have to b a multiple of the record size. Only fully written records would be persisted, a partially written record would automatically get overwritten by the next write. That way the SetOffset call needed currently for the commit log file can be implicitly realized by the logic inside appendable itself.
