### ISSUE TITLE
Reproducible databases (option for no server timestamp in hash)

### ISSUE THREAD

**Issue by MikeBeller** [codenotary/immudb#889]
Please add the ability to run immudb, or an immudb database, in "reproducible" mode -- where the server commit timestamp is not included in the hash.

Use case: I am feeding my database from Kafka for example.  With databases other than Immudb, if I  need to reload, or if I want to run parallel database replicas, I can just load them independently from the Kafka queue and the databases will be identical from all important perspectives.  Not the case with Immudb, as the series of hashes will not be reproducible.  The timestamps will be different.

If Immudb had a "don't put your timestamps in this database" option, then this would solve my problem.  If that idea doesn't work because Immudb needs timestamps for some reason, then if I could supply the timestamp through the API, that would probably be ok too.  ( I would just make it part of the message persisted in the Kafka queue and would feed it into the API when I reload.)

**Comment by jeroiraz** [comment]
Thanks for creating this enhancement request @MikeBeller

**Comment by jeroiraz** [comment]
Hi @MikeBeller, we've a PR associated to this feature request. Would you like building immudb with the associated branch?

User created databases either using immuadmin or an sdk would be reproducible by setting `exclude-commit-time` flag or `ExcludeCommitTime` attribute.

**Comment by MikeBeller** [comment]
Great!  I was able to build the reproducible_stores branch, start immudb, create two databases, and put the same k/v pairs in them in the same order -- got the same hashes.  Thanks for this!  Looking forward to seeing it merged.  

![Screen Shot 2021-09-06 at 3 03 50 PM](https://user-images.githubusercontent.com/1700778/132254675-f81b9b4e-415f-4fb1-973b-2c43e37c1b57.png)

**Comment by victornor** [comment]
> Hi @MikeBeller, we've a PR associated to this feature request. Would you like building immudb with the associated branch?
> 
> User created databases either using immuadmin or a sdk would be reproducible by setting `exclude-commit-time` flag or `ExcludeCommitTime` attribute.

Where is this CommitTime accessible? I'm asking here because i see no mention about history timestamps or commit times anywhere else, so I'm wondering if this is something we can access?

I want to compare linux access times to key/value history change timestamps, so that I'm able to determine if a value change was made during an ssh connection to the server.

Is this possible?

**Comment by jeroiraz** [comment]
> > Hi @MikeBeller, we've a PR associated to this feature request. Would you like building immudb with the associated branch?
> > User created databases either using immuadmin or a sdk would be reproducible by setting `exclude-commit-time` flag or `ExcludeCommitTime` attribute.
> 
> Where is this CommitTime accessible? I'm asking here because i see no mention about history timestamps or commit times anywhere else, so I'm wondering if this is something we can access?
> 
> I want to compare linux access times to key/value history change timestamps, so that I'm able to determine if a value change was made during an ssh connection to the server.
> 
> Is this possible?

aham, interesting

Currently by excluding the commit time, the transaction time is not written. This change was introduced before replication was built-in in immudb, so probably the need of this is reduced to certain use cases. I mean excluding the commit time.

Key-Values itself does not get a time associated as all the entries within the same transaction are atomically stored as part of the same transaction.

While validating the time was not altered by doing time value comparison could be done (using transaction timestamp), it may not be as strong as hash calculation done with the cryptographic proofs. Which is done using the verified methods using a sdk.

I may be missing some things, please feel free to further expand your ideas, either here or in Discord channel or by starting a Discussion topic in github

**Comment by MikeBeller** [comment]
Hi Jeronimo.  Thanks so much for getting back to me on this one.
 Unfortunately meanwhile I moved on to other projects and am not in a
position to focus on immudb right now.  If it turns out it is relevant in
an upcoming project I will definitely try it out again.   The product is
very intriguing and I hope some day to get back to it.
Mike
