### ISSUE TITLE
Allow composite primary key

### ISSUE THREAD

**Issue by diogomoreira** [codenotary/immudb#903]
**What would you like to be added or enhanced**

It should be possible to create a table with a **composite primary key** (a primary key that consists of two or more columns) as in `PRIMARY KEY (id, column1, column2)`. Currrently, when trying to create a table with composite primary key, the following error raises: `Syntax error: unexpected '(', expecting IDENTIFIER` and it's only possible to create tables with only one column as primary key, and the syntax with parenthesis `PRIMARY KEY (id)` isn't work either, even with just one column.

**Why is this needed**

In some tables a single column is not enough by itself to uniquely identify a row.

**Comment by jeroiraz** [comment]
Hi @diogomoreira, we've included composite primary key support into an ongoing development effort. Would you like building immudb from the branch of the PR `https://github.com/codenotary/immudb/pull/900` and check if things are working as you'd expect?

This PR is still in progress so you might still find some issues. Please let us know whatever you find.

Note: You may need to start with a fresh database e.g. no data folder in current path.

**Comment by diogomoreira** [comment]
Hi @jeroiraz, just built the Docker image from PR and everything is working as expected. I was able to create a table with a composite primary key 👍🏻

**Comment by jeroiraz** [comment]
Thanks a lot @diogomoreira
