### ISSUE TITLE
unexpected ERROR:  max key length exceeded on INSERT

### ISSUE THREAD

**Issue by mmeloni** [codenotary/immudb#935]
**What happened**
```
CREATE TABLE profiles (id INTEGER AUTO_INCREMENT,refer INTEGER,name VARCHAR[256],role VARCHAR[256],PRIMARY KEY ID);
CREATE INDEX ON profiles (name);
INSERT INTO profiles (refer,name,role) VALUES (2, 'my', 'key');
```
returns 
ERROR:  max key length exceeded

**What you expected to happen**
no error
**How to reproduce it (as minimally and precisely as possible)**

**Environment**
```shell
# run "immu* version" and copy/paste the output here
```

**Additional info (any other context about the problem)**

**Comment by jeroiraz** [comment]
the issue is due to a validation on the max length not taking into account encoded len (4 bytes). So until this is fixed, max size would be 256-4 = 252 e.g. varchar[252]
