### ISSUE TITLE
Uploading 1.1.0 to AWS

### ISSUE THREAD

**Issue by zaza81** [codenotary/immudb#937]
**What would you like to be added or enhanced**

The AMI image on AWS is 1.0.1, we should upload version 1.1.0

https://aws.amazon.com/marketplace/pp/prodview-cctrj4cvxmzvq?sr=0-1&ref_=beagle&applicationId=AWSMPContessa

**Why is this needed**
Users should get the last version with box fixes and new features

**Additional context**

Ideally we should build a pipeline for automating the build.

**Comment by ufierro** [comment]
@SimoneLazzaris took care of this last week, closing issue
