### ISSUE TITLE
Updating GO SDK

### ISSUE THREAD

**Issue by zaza81** [codenotary/immudb#972]
When changing database, the context has to also changed. This is either a bug or a very unintuitive way to change database

NOTE:

Now there is the possibility to use the in memory token service that make this possible.
```
WithTokenService(tokenservice.NewInmemoryTokenService())
```
Probably yesterday @Ilya tried with the default fileTokenService.
I planned to make it as default asap ( instead of the fileTokenService )

**Comment by zaza81** [comment]
@mmeloni  I guess this is not valid anymore as we changed the way we handle the connection?

**Comment by mmeloni** [comment]
Yes, but also without session token is now handled internally by SDK. We can close this
