### ISSUE TITLE
Unintuitive authentication mechanism

### ISSUE THREAD

**Issue by zaza81** [codenotary/immudb#974]
token should be an internal property of the connection and not passed around in the context object, context should still be passed to propagate cancellation from upper layers (like cancellation of http handler that connects to immudb)

NOTE:
at the moment token can be handled internally using inMemoryTokenService. We miss context  propagation

**Comment by mmeloni** [comment]
Context propagation is already in. Cancel and deadline events are handled by GRPC server natively.
I updated doc on immudb.io repo https://github.com/codenotary/immudb.io/pull/92 and also examples https://github.com/codenotary/immudb-client-examples/pull/17
