### ISSUE TITLE
Quickstart review

### ISSUE THREAD

**Issue by zaza81** [codenotary/immudb#977]
- [x]  Missing information on how to create other databases
- [x]  Missing information on how to switch to other databases
- [x]  When using time travel, we don’t know where to get the transaction number from - we should show this to the user after committing data (this may be a missing capability in immudb / tools).
- [ ]  The last long query example in the quick start is incorrect (incorrect result in the example)
- [ ]  No easy method to retrieve the whole history -> improve docs

**Comment by anantasty** [comment]
@zaza81 I would like to take care of this as my first issue. 
The [quickstart](https://github.com/codenotary/immudb#quickstart) in the Readme does not seem to have much detail on the operations - delete, create list history etc. But the [docs here](https://docs.immudb.io/master/quickstart.html#getting-immudb-running). Seem to have all the details but I am not able to find the repository for it. What is the appropriate location for this information?

**Comment by byo** [comment]
Hi @anantasty, thank you for your interest in this issue.

The documentation is in a separate repository: https://github.com/codenotary/immudb.io. The documentation for next release is in src/master folder (we freeze that into a specific version during the release).

**Comment by anantasty** [comment]
Thanks @byo I can add some more information to the todo there.

**Comment by anantasty** [comment]
Addressed in #127
https://github.com/codenotary/immudb.io/pull/127

**Comment by tomekkolo** [comment]
old one, docs being refreshed.
