### ISSUE TITLE
Any thought to having P2P distributed nodes

### ISSUE THREAD

**Issue by lonnietc** [codenotary/immudb#995]
Hi All,

I am still exploring Immudb a lot and like the blockchain approach for being immutable but as also just wondering about what challenges there might be in setting it up to work on something like libP2P or some other highly distributable network so that Immudb could access and query databases and tables on different and remote nodes?

Also, I had the idea of having a singular distributed database spanning many remote nodes or even a singular TABLE spanning many, perhaps thousands of remote nodes aggregated into a single virtual database or virtual table.

Just some ideas and thoughts that cam to mind when initially play around with Immudb.

Any thoughts on any of this?
Cheers and have be a great weekend

**Comment by byo** [comment]
Hi @lonnietc,

We had some very initial internal discussions about such decentralized approach although nothing concrete yet.

Our current focus is to ensure immudb has all the features expected from a general-purpose database and there's still a lot to do in this area and it will keep us busy for some time ;)

Some initial steps towards storing the data in the "cloud" were already made with the `S3` storage support, it's still bottlenecked by a single immudb instance running on top of it but we already discussed some options to add read-only replicas to easily scale read operations horizontally.

Regards
